### ISSUE TITLE
AIR 21 TextInput Skin

### ISSUE THREAD

**Issue by leossmith** [quick6black/flex-Android-Material-Skins#1]
So in AIR 21 they added textinput compatibility for softkeyboard types. Would you be able to add the StageTextInput skin? Stage comes with scrolling and overlay problems, so the TextInput will solve some problems :)

**Comment by quick6black** [comment]
I will look at that this week, downloading AIR 21 now.

**Comment by leossmith** [comment]
Thanks.

**Comment by quick6black** [comment]
I looked over the release notes for Air 21 and did not see anything related to what you were talking about. I did remember this getting fixed in an earlier version of the Flex SDK, so I copied over the ScrollingStageTextArea and ScrollingStageTextInput from the Flex SDK and then updated View1 to show how to use them. This does allow for scrolling without any issues, I am going to close this for now. If this is different then what you are talking about can you update with a web link to what you are referring to.
